%%%%%%%%%%%%%%%%%% Don't Change This %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[a4paper, 12pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[sc]{mathpazo} % math fonts
\usepackage{xcolor} % color


\newcommand{\HWNumber}[1]{%
  \expandafter\newcommand\csname hwnumber\endcsname{#1}%
} 
\newcommand{\Semester}[1]{%
  \expandafter\newcommand\csname semest\endcsname{#1}%
} 
\newcommand{\Student}[1]{%
  \expandafter\newcommand\csname stdnt\endcsname{#1}%
} 

\newcommand{\Course}[1]{%
  \expandafter\newcommand\csname crse\endcsname{#1}%
} 


\title{\vspace{-.5in}\textmd{\textbf{\ Homework \# \hwnumber}}\\\crse\\\normalsize\semest\vspace{0in}}
\date{}
\author{\textbf{\stdnt}\normalsize\vspace{0.1in}}

% Typical maths and symbols resource packages
\usepackage{amsmath,amsfonts,amscd,amsthm,amstext,amsbsy,amssymb,latexsym,bm,url} 

% This allows in-text hyperlinks
\usepackage[unicode=true,pdfusetitle, bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2, breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=true]{hyperref}
\hypersetup{
pdfstartview={XYZ null null 1},
colorlinks, 
linkcolor=red,
urlcolor=blue,
anchorcolor=red,
     }

\usepackage{breakurl} % for long URLs

%This sets page margins wide, which can be helpful for wide R output
\usepackage{geometry}
\geometry{verbose,tmargin=1.25in,bmargin=1in,lmargin=.5in,rmargin=.5in}

\usepackage{parskip}
\setlength{\parindent}{0in} % remove indentation of paragraphs


% Allows control over headers and footers
\usepackage{fancyhdr}
\renewcommand{\footrulewidth}{0.4pt}
\pagestyle{fancy} 
\rhead{\textbf{\crse} HW\# \hwnumber }
\chead{}
\lhead{\stdnt }
 \cfoot{}
\lfoot{\semest}
\rfoot{\thepage}

\fancypagestyle{plain}{%
  \renewcommand{\headrulewidth}{0pt}%
   \fancyhf{}%
}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%% Optional Packages %%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{booktabs,longtable,threeparttable} % Table options
\usepackage{graphicx,float} % To load and manipulate graphcis
\usepackage{rotating} % for rotating floats and sideways table 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% FYI %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \textbf{} makes the argument print bold
% \emph{} makes the argument print italicized
% The percent sign, %, is a comment. Nothing after it on the same line will be used
% \texttt{} makes the argument true type (i.e., typewriter font)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%% COMPLETE THE INFORMATION IN THIS BOX %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\HWNumber{1} % Homework Number

\Student{Kari Hodge} % For Multiple Authors: Student NameA \and Student NameB

\Course{Challenge 15- R} % Fill in the Course number here
\Semester{July 22, 2021} % Fill in the Semester here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Formally begin the document and make the title.
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\maketitle
%  This makes a TOC 
\tableofcontents


%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Knitr output options %%%%%%%%%%%%%%%%

% Send some options to R





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Introduction}
  AutosRUs’ newest prototype, the MechaCar, is suffering from production troubles that are blocking the manufacturing team’s progress. The following analysis will be performed:
\begin{enumerate}
\item Perform multiple linear regression analysis to identify which variables   in the dataset predict the mpg of MechaCar prototypes. 
\item Collect summary statistics on the pounds per square inch (PSI) of the     suspension coils from the manufacturing lots. 
\item Run t-tests to determine if the manufacturing lots are statistically           different from the mean population. 
\item Design a statistical study to compare vehicle performance of the              MechaCar vehicles against vehicles from other manufacturers. For each       statistical analysis, you’ll write a summary interpretation of the          findings.
\end{enumerate}
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# read in both data sets}
\hlstd{mecha}\hlkwb{<-}\hlkwd{read.csv}\hlstd{(}\hlkwc{file}\hlstd{=}\hlstr{'/Users/karihodge/Dropbox/UT_Data_Camp/Class_Folder/R-AutosRUs/MechaCar_mpg.csv'}\hlstd{,}\hlkwc{check.names}\hlstd{=F,}\hlkwc{stringsAsFactors} \hlstd{= F)}
\hlkwd{head}\hlstd{(mecha)}
\end{alltt}
\begin{verbatim}
##   vehicle_length vehicle_weight spoiler_angle
## 1       14.69710       6407.946      48.78998
## 2       12.53421       5182.081      90.00000
## 3       20.00000       8337.981      78.63232
## 4       13.42849       9419.671      55.93903
## 5       15.44998       3772.667      26.12816
## 6       14.45357       7286.595      30.58568
##   ground_clearance AWD      mpg
## 1         14.64098   1 49.04918
## 2         14.36668   1 36.76606
## 3         12.25371   0 80.00000
## 4         12.98936   1 18.94149
## 5         15.10396   1 63.82457
## 6         13.10695   0 48.54268
\end{verbatim}
\begin{alltt}
\hlstd{susp}\hlkwb{<-}\hlkwd{read.csv}\hlstd{(}\hlkwc{file}\hlstd{=}\hlstr{'/Users/karihodge/Dropbox/UT_Data_Camp/Class_Folder/R-AutosRUs/Suspension_Coil.csv'}\hlstd{,}\hlkwc{check.names}\hlstd{=F,}\hlkwc{stringsAsFactors} \hlstd{= F)}
\hlkwd{head}\hlstd{(susp)}
\end{alltt}
\begin{verbatim}
##   VehicleID Manufacturing_Lot  PSI
## 1    V40858              Lot1 1499
## 2    V40607              Lot1 1500
## 3    V31443              Lot1 1500
## 4     V6004              Lot1 1500
## 5     V7000              Lot1 1501
## 6    V17344              Lot1 1501
\end{verbatim}
\end{kframe}
\end{knitrout}

\section{Deliverable 1}
\textbf{Deliverable 1:} Linear Regression to Predict MPG

The MechaCar datavset contains mpg test results for 50 prototype MechaCars. The MechaCar prototypes were produced using multiple design specifications to identify ideal vehicle performance. Multiple metrics, such as vehicle length, vehicle weight, spoiler angle, drivetrain, and ground clearance, were collected for each vehicle.

\subsection{Test Normality}

Evaluate Skewness and Kurtosis
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(psych)}
\hlkwd{describe}\hlstd{(mecha)}
\end{alltt}
\begin{verbatim}
##                  vars  n    mean      sd  median trimmed
## vehicle_length      1 50   15.02    2.03   14.60   14.83
## vehicle_weight      2 50 6154.15 1846.09 5928.69 6122.17
## spoiler_angle       3 50   57.12   19.56   58.55   58.06
## ground_clearance    4 50   12.71    2.53   12.98   12.71
## AWD                 5 50    0.50    0.51    0.50    0.50
##                      mad  min   max range  skew kurtosis
## vehicle_length      1.78   12    20     8  0.76    -0.28
## vehicle_weight   1802.33 2000 10000  8000  0.13    -0.52
## spoiler_angle      15.75    0    90    90 -0.53     0.04
## ground_clearance    2.55    6    18    12 -0.16    -0.29
## AWD                 0.74    0     1     1  0.00    -2.04
##                      se
## vehicle_length     0.29
## vehicle_weight   261.08
## spoiler_angle      2.77
## ground_clearance   0.36
## AWD                0.07
##  [ reached 'max' / getOption("max.print") -- omitted 1 rows ]
\end{verbatim}
\end{kframe}
\end{knitrout}

The descriptive statistics summary provides evidence that the variables are not normally distributed. Skewness values should be near 0 and kurtosis near 3. Only vehicle length and AWD meet the skewness criteria and non of the variables meet kurtosis. 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Test of Normality}
\hlcom{# # plot the distribution using the geom_density() function}
\hlcom{# put plots together}
\hlkwd{library}\hlstd{(ggplot2)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# \\\#\# Attaching package: 'ggplot2'}}

{\ttfamily\noindent\itshape\color{messagecolor}{\#\# The following objects are masked from 'package:psych':\\\#\# \\\#\#\ \ \ \  \%+\%, alpha}}\begin{alltt}
\hlkwd{library}\hlstd{(gridExtra)}
\hlcom{# create plots and name them}
\hlstd{plot1}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=vehicle_length))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlstd{plot2}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=vehicle_weight))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlstd{plot3}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=spoiler_angle))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlstd{plot4}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=ground_clearance))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlstd{plot5}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=AWD))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlstd{plot6}\hlkwb{<-}\hlkwd{ggplot}\hlstd{(mecha,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=mpg))} \hlopt{+} \hlkwd{geom_density}\hlstd{()}
\hlcom{# arrange plots }
\hlkwd{grid.arrange}\hlstd{(plot1, plot2, plot3, plot4,plot5, plot6,}  \hlkwc{nrow} \hlstd{=} \hlnum{2}\hlstd{,} \hlkwc{ncol} \hlstd{=} \hlnum{3}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/regressionHW-unnamed-chunk-3-1} 

}



\end{knitrout}
According to the plots the variables are not normal. 
AWD is not continuous. 

Shapiro-Wilk test of Normality
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{vl}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{vehicle_length)}
\hlstd{vw}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{vehicle_weight)}
\hlstd{sa}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{spoiler_angle)}
\hlstd{gc}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{ground_clearance)}
\hlstd{awd}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{AWD)}
\hlstd{mpg}\hlkwb{<-}\hlkwd{shapiro.test}\hlstd{(mecha}\hlopt{$}\hlstd{mpg)}

\hlcom{# create table with p-values in latex syntax}
\end{alltt}
\end{kframe}
\end{knitrout}

\begin{table}[ht]
\centering
\caption{Shaprio Test of Normality}\label{tab:LongTable}
\begin{tabular}{ccc}\toprule
 Variable & P Value & Normality\\ \midrule
 vehicle length & 0.01 & No \\ 
 vehicle weight & 0.82 & Yes \\  
 spoiler angle & 0.28 & Yes \\
 ground clearance & 0.84 & Yes \\
 AWD & 0.00 & No \\
 mpg & 0.79 & Yes 
 \bottomrule
\end{tabular}
\end{table}

The Shapiro-Wilk test of normality hypothesis states that the distribution is normal. Vehicle weight, spoiler angle, ground-clearance, and mpg provide evidence that they are distributed normally with p-vales greater than 0.05. 

However, based on all of the evidence the variable are not normally distributed and a non-parametric model should be used. 

Correlation Matrix
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# using the used_cars data set }
\hlcom{# select numeric columns and convert to matrix}
\hlstd{mecha_matrix} \hlkwb{<-} \hlkwd{as.matrix}\hlstd{(mecha[,}\hlkwd{c}\hlstd{(}\hlstr{"vehicle_length"}\hlstd{,}\hlstr{"vehicle_weight"}\hlstd{,}\hlstr{"spoiler_angle"}\hlstd{,} \hlstr{"ground_clearance"}\hlstd{,} \hlstr{"AWD"}\hlstd{,} \hlstr{"mpg"}\hlstd{)])}
\hlcom{#used_matrix}
\hlkwd{cor}\hlstd{(mecha_matrix)}
\end{alltt}
\begin{verbatim}
##                  vehicle_length vehicle_weight
## vehicle_length       1.00000000    -0.12271790
## vehicle_weight      -0.12271790     1.00000000
## spoiler_angle        0.02577114    -0.11307851
## ground_clearance    -0.31663112     0.08511338
## AWD                  0.08565668    -0.03698098
## mpg                  0.60947984     0.09068314
##                  spoiler_angle ground_clearance         AWD
## vehicle_length      0.02577114      -0.31663112  0.08565668
## vehicle_weight     -0.11307851       0.08511338 -0.03698098
## spoiler_angle       1.00000000      -0.21112057 -0.09120266
## ground_clearance   -0.21112057       1.00000000 -0.15214456
## AWD                -0.09120266      -0.15214456  1.00000000
## mpg                -0.02083999       0.32874886 -0.14166977
##                          mpg
## vehicle_length    0.60947984
## vehicle_weight    0.09068314
## spoiler_angle    -0.02083999
## ground_clearance  0.32874886
## AWD              -0.14166977
## mpg               1.00000000
\end{verbatim}
\end{kframe}
\end{knitrout}
Vehicle length and ground clearance or the only variables that are somewhat correlated to mpg. The estimates from the regression model may be suspect. 


\subsection{Non-Parametnric Multiple Regression}

A Generalized additive model will be used in place of a multiple linear regression model as the GAM model is more flexible with a variety of variables. 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(mgcv)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# Loading required package: nlme}}

{\ttfamily\noindent\itshape\color{messagecolor}{\#\# This is mgcv 1.8-36. For overview type 'help("{}mgcv-package"{})'.}}\begin{alltt}
\hlstd{model.g} \hlkwb{=} \hlkwd{gam}\hlstd{(mpg} \hlopt{~} \hlstd{vehicle_length} \hlopt{+} \hlstd{vehicle_weight} \hlopt{+} \hlstd{spoiler_angle} \hlopt{+} \hlstd{ground_clearance} \hlopt{+} \hlstd{AWD,}
              \hlkwc{data} \hlstd{= mecha,}
              \hlkwc{family}\hlstd{=}\hlkwd{gaussian}\hlstd{())}

\hlkwd{summary}\hlstd{(model.g)}
\end{alltt}
\begin{verbatim}
## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + 
##     AWD
## 
## Parametric coefficients:
##                    Estimate Std. Error t value Pr(>|t|)    
## (Intercept)      -1.040e+02  1.585e+01  -6.559 5.08e-08 ***
## vehicle_length    6.267e+00  6.553e-01   9.563 2.60e-12 ***
## vehicle_weight    1.245e-03  6.890e-04   1.807   0.0776 .  
## spoiler_angle     6.877e-02  6.653e-02   1.034   0.3069    
## ground_clearance  3.546e+00  5.412e-01   6.551 5.21e-08 ***
## AWD              -3.411e+00  2.535e+00  -1.346   0.1852    
## ---
## Signif. codes:  
## 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## 
## R-sq.(adj) =  0.683   Deviance explained = 71.5%
## GCV = 87.489  Scale est. = 76.99     n = 50
\end{verbatim}
\end{kframe}
\end{knitrout}

THe p-value is 5.77 x 10^-6, and  is much smaller than the 0.05 a priori significance level. There is significant evidence to reject the null that the slope of our line is zero. 
Based on the p-values for this model vehicle weight, spoiler angle and AWD are not significant predictors in the variance of mpg. 
Vehicle length and ground clearance are statistically significant, meaning that there is significant evidence to reject the null that the slope of our line is zero. Holding all other variable constant for a one unit increase in mpg vehicle length increases 6.267e+00 units. Holding all other variable constant for a one unit increase in mpg ground clearance increases 3.546e+00 units. 
The intercept is statistically significant, it means that the intercept term explains a significant amount of variability in the dependent variable when all independent variables are equal to zero. This is an indication that the model is not explaining variability in the dependent variable. 
Adjusted R-squared is 0.68 meaning that the model explains 68\% of the variability in mpg.  




\section{Deliverable 2}
\textbf{Deliverable 2:} Summary Statistics on Suspension Coils

The MechaCar Suspension Coi data set contains the results from multiple production lots. In this data set, the weight capacities of multiple suspension coils were tested to determine if the manufacturing process is consistent across production lots. Analysis will include:

\begin{enumerate}
\item The suspension coil’s PSI continuous variable across all manufacturing lots. 
\item The following PSI metrics for each lot: mean, median, variance, and       standard deviation. 
\end{enumerate}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{head}\hlstd{(susp)}
\end{alltt}
\begin{verbatim}
##   VehicleID Manufacturing_Lot  PSI
## 1    V40858              Lot1 1499
## 2    V40607              Lot1 1500
## 3    V31443              Lot1 1500
## 4     V6004              Lot1 1500
## 5     V7000              Lot1 1501
## 6    V17344              Lot1 1501
\end{verbatim}
\begin{alltt}
\hlkwd{library}\hlstd{(tidyverse)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# -- Attaching packages ------------------- tidyverse 1.3.1 --}}

{\ttfamily\noindent\itshape\color{messagecolor}{\#\# v tibble\ \ 3.1.2\ \ \ \  v dplyr\ \  1.0.7\\\#\# v tidyr\ \  1.1.3\ \ \ \  v stringr 1.4.0\\\#\# v readr\ \  1.4.0\ \ \ \  v forcats 0.5.1\\\#\# v purrr\ \  0.3.4}}

{\ttfamily\noindent\itshape\color{messagecolor}{\#\# -- Conflicts ---------------------- tidyverse\_conflicts() --\\\#\# x ggplot2::\%+\%()\ \ \ \ masks psych::\%+\%()\\\#\# x ggplot2::alpha()\ \ masks psych::alpha()\\\#\# x dplyr::collapse() masks nlme::collapse()\\\#\# x dplyr::combine()\ \ masks gridExtra::combine()\\\#\# x dplyr::filter()\ \  masks stats::filter()\\\#\# x dplyr::lag()\ \ \ \ \ \ masks stats::lag()}}\begin{alltt}
\hlcom{# summarize PSI}
\hlstd{total_summary}\hlkwb{<-}\hlkwd{summarise}\hlstd{(susp,} \hlkwc{Mean}\hlstd{=}\hlkwd{mean}\hlstd{(PSI),} \hlkwc{Median}\hlstd{=}\hlkwd{median}\hlstd{(PSI),} \hlkwc{Variance}\hlstd{=}\hlkwd{sd}\hlstd{(PSI)}\hlopt{^}\hlnum{2}\hlstd{,} \hlkwc{SD}\hlstd{=}\hlkwd{sd}\hlstd{(PSI))}
\hlstd{total_summary}
\end{alltt}
\begin{verbatim}
##      Mean Median Variance       SD
## 1 1498.78   1500 62.29356 7.892627
\end{verbatim}
\begin{alltt}
\hlcom{# summarize PSI by lot}

\hlstd{lot_summary}\hlkwb{<-} \hlstd{susp} \hlopt{%>%} \hlkwd{group_by}\hlstd{(Manufacturing_Lot)} \hlopt{%>%} \hlkwd{summarise}\hlstd{(}\hlkwc{Mean}\hlstd{=}\hlkwd{mean}\hlstd{(PSI),} \hlkwc{Median}\hlstd{=}\hlkwd{median}\hlstd{(PSI),} \hlkwc{Variance}\hlstd{=}\hlkwd{sd}\hlstd{(PSI)}\hlopt{^}\hlnum{2}\hlstd{,} \hlkwc{SD}\hlstd{=}\hlkwd{sd}\hlstd{(PSI),} \hlkwc{.groups} \hlstd{=} \hlstr{'keep'}\hlstd{)}
\hlstd{lot_summary}
\end{alltt}
\begin{verbatim}
## # A tibble: 3 x 5
## # Groups:   Manufacturing_Lot [3]
##   Manufacturing_Lot  Mean Median Variance     SD
##   <chr>             <dbl>  <dbl>    <dbl>  <dbl>
## 1 Lot1              1500   1500     0.980  0.990
## 2 Lot2              1500.  1500     7.47   2.73 
## 3 Lot3              1496.  1498.  170.    13.0
\end{verbatim}
\end{kframe}
\end{knitrout}

The design specifications for the MechaCar suspension coils dictate that the variance of the suspension coils must not exceed 100 pounds per square inch. Lot 3 variance is 170 and is higher than the maximum allowable pounds per square inch. Lot 1 and 2 are with in acceptable ranges. 




\section{Deliverable 3}
\textbf{Deliverable 3:} T-Test on Suspension Coils

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# determine if the PSI across all manufacturing lots is statistically different from the population mean of 1,500 pounds per square inch.}
\hlkwd{describe}\hlstd{(susp}\hlopt{$}\hlstd{PSI)}
\end{alltt}
\begin{verbatim}
##    vars   n    mean   sd median trimmed  mad  min  max
## X1    1 150 1498.78 7.89   1500 1499.66 1.48 1452 1542
##    range  skew kurtosis   se
## X1    90 -1.69    17.63 0.64
\end{verbatim}
\begin{alltt}
\hlkwd{t.test}\hlstd{(susp}\hlopt{$}\hlstd{PSI,} \hlkwc{mu}\hlstd{=}\hlnum{1500}\hlstd{)}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  susp$PSI
## t = -1.8931, df = 149, p-value = 0.06028
## alternative hypothesis: true mean is not equal to 1500
## 95 percent confidence interval:
##  1497.507 1500.053
## sample estimates:
## mean of x 
##   1498.78
\end{verbatim}
\begin{alltt}
\hlcom{# non-parametric t-test for comparison}
\hlkwd{wilcox.test}\hlstd{(susp}\hlopt{$}\hlstd{PSI,}\hlnum{1500}\hlstd{)}
\end{alltt}
\begin{verbatim}
## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  susp$PSI and 1500
## W = 68.5, p-value = 0.8894
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}
\end{kframe}
\end{knitrout}

The Variable PSI is not nomrally distributed and  a non parametric t-test should be used. 

The null hypothesis for this t-test is that the sample mean for PSI is statistically similar to the population mean. According the p-value, we do not have sufficient evidence to reject this hypothesis because the p-value is greater than than the Type I error rate of 5\%.
There is 95\% confidence that the population mean of PSI is between 1497.51 and 1500.05. 

Complimentary to the t-test the wilcox non parametric equivilant to the t-test conclusion is the same. There is not have sufficient evidence to reject this hypothesis because the p-value is greater than than the Type I error rate of 5\%.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# determine if the PSI for each manufacturing lot is statistically different from the population mean of 1,500 pounds per square inch.}
\hlstd{lo1}\hlkwb{<-}\hlstd{susp[susp}\hlopt{$}\hlstd{Manufacturing_Lot}\hlopt{==} \hlstr{"Lot1"}\hlstd{,]}
\hlkwd{t.test}\hlstd{(lo1}\hlopt{$}\hlstd{PSI,} \hlkwc{mu}\hlstd{=}\hlnum{1500}\hlstd{)}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  lo1$PSI
## t = 0, df = 49, p-value = 1
## alternative hypothesis: true mean is not equal to 1500
## 95 percent confidence interval:
##  1499.719 1500.281
## sample estimates:
## mean of x 
##      1500
\end{verbatim}
\begin{alltt}
\hlstd{lo2}\hlkwb{<-}\hlstd{susp[susp}\hlopt{$}\hlstd{Manufacturing_Lot}\hlopt{==} \hlstr{"Lot2"}\hlstd{,]}
\hlkwd{t.test}\hlstd{(lo2}\hlopt{$}\hlstd{PSI,} \hlkwc{mu}\hlstd{=}\hlnum{1500}\hlstd{)}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  lo2$PSI
## t = 0.51745, df = 49, p-value = 0.6072
## alternative hypothesis: true mean is not equal to 1500
## 95 percent confidence interval:
##  1499.423 1500.977
## sample estimates:
## mean of x 
##    1500.2
\end{verbatim}
\begin{alltt}
\hlstd{lo3}\hlkwb{<-}\hlstd{susp[susp}\hlopt{$}\hlstd{Manufacturing_Lot}\hlopt{==} \hlstr{"Lot3"}\hlstd{,]}
\hlkwd{t.test}\hlstd{(lo3}\hlopt{$}\hlstd{PSI,} \hlkwc{mu}\hlstd{=}\hlnum{1500}\hlstd{)}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  lo3$PSI
## t = -2.0916, df = 49, p-value = 0.04168
## alternative hypothesis: true mean is not equal to 1500
## 95 percent confidence interval:
##  1492.431 1499.849
## sample estimates:
## mean of x 
##   1496.14
\end{verbatim}
\begin{alltt}
\hlcom{# determine if PSI by lot is statistically different a kin to Anova and doing it this way increase chances of making a type I error.}
\hlkwd{t.test}\hlstd{(}\hlkwc{formula}\hlstd{= PSI}\hlopt{~}\hlstd{Manufacturing_Lot,} \hlkwc{data}\hlstd{= susp,} \hlkwc{subset}\hlstd{= Manufacturing_Lot} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{'Lot1'}\hlstd{,}\hlstr{'Lot2'}\hlstd{))}
\end{alltt}
\begin{verbatim}
## 
## 	Welch Two Sample t-test
## 
## data:  PSI by Manufacturing_Lot
## t = -0.48653, df = 61.635, p-value = 0.6283
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.0218165  0.6218165
## sample estimates:
## mean in group Lot1 mean in group Lot2 
##             1500.0             1500.2
\end{verbatim}
\begin{alltt}
\hlkwd{t.test}\hlstd{(}\hlkwc{formula}\hlstd{= PSI}\hlopt{~}\hlstd{Manufacturing_Lot,} \hlkwc{data}\hlstd{= susp,} \hlkwc{subset}\hlstd{= Manufacturing_Lot} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{'Lot1'}\hlstd{,}\hlstr{'Lot3'}\hlstd{))}
\end{alltt}
\begin{verbatim}
## 
## 	Welch Two Sample t-test
## 
## data:  PSI by Manufacturing_Lot
## t = 2.0856, df = 49.564, p-value = 0.04218
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.1418273 7.5781727
## sample estimates:
## mean in group Lot1 mean in group Lot3 
##            1500.00            1496.14
\end{verbatim}
\begin{alltt}
\hlkwd{t.test}\hlstd{(}\hlkwc{formula}\hlstd{= PSI}\hlopt{~}\hlstd{Manufacturing_Lot,} \hlkwc{data}\hlstd{= susp,} \hlkwc{subset}\hlstd{= Manufacturing_Lot} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{'Lot2'}\hlstd{,}\hlstr{'Lot3'}\hlstd{))}
\end{alltt}
\begin{verbatim}
## 
## 	Welch Two Sample t-test
## 
## data:  PSI by Manufacturing_Lot
## t = 2.1533, df = 53.29, p-value = 0.03584
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.278647 7.841353
## sample estimates:
## mean in group Lot2 mean in group Lot3 
##            1500.20            1496.14
\end{verbatim}
\end{kframe}
\end{knitrout}

\begin{table}[ht]
\centering
\caption{Shaprio Test of Normality}\label{tab:LongTable}
\begin{tabular}{ccc}\toprule
 Manufacturing Lot & Mean & P Value & Mean Difference & Confidence Interval\\ \midrule
 Lot1 & 1500.00 & 1 & 0 & 1499.719, 1500.281 \\ 
 Lot2 & 1500.20 & 0.61 &  0.2 & 1499.42, 1500.98 \\  
 Lot3 & 1496.14  & 0.04 & -4.06 & 1492.43, 1499.85 \\
 \bottomrule
\end{tabular}
\end{table}


The null hypothesis for this t-test is that the sample mean for PSI is statistically similar to the population mean. According the p-value for Lot1 and Lot2, we do not have sufficient evidence to reject this hypothesis because the p-value is greater than than the Type I error rate of 5\%.
There is 95\% confidence that the population mean of PSI for Lot 1 is between 1499.719 and 1500.281. There is 95\% confidence that the population mean of PSI for Lot 2 is between 1499.42 and 1500.98. Notice that 1500 is in the confidence interval for these two lots. There is 95\% confidence that the population mean of PSI for Lot 3 is between 1492.43 and 1499.85.Notice that 1500 is not in the confidence interval for Lot 3. 


\section{Deliverable 4}
\textbf{Deliverable 4:} Design a Study Comparing the MechaCar to the Competition

This study design  will compare performance of the MechaCar vehicles against performance of vehicles from other manufacturers. A google search of how to compare cars turned up cars.com research comparison site website (https://www.cars.com/research/compare/). According to cars site the following perfromace features are used for comparison: MSRP, MPG, drivetrain, safety features. J.D. Power NADA guide compares two additional variable engine and transmission. 

Based on the google search the variables that will be included in this study include: consumer ratings, car class, MSRP, MPG, drivetrain, engine, transmission, safety, and consumer ratings. 

The first step will be to evaluate the data for data type and normality. 
The second step will be to create a correlation matrix to evaluate the relationship of the variables. 
Next Consumer ratings will be used as a dependent variable in a categorical multiple regression model to estimate how much variability is explained in consumer ratings by all of the other variables. 
Using the output of the regression variables that contribute the most to the variability in consumer ratings will be used in the ANOVA analysis to compare Mechacar vehicles by car class to other vehicles in that class. ANOVA will be used as there are multiple categorical variables being used compare Mechacar to other vehicles. 
In the ANOVA analysis the null hypothesis is that there is no difference between Mechacar and other vehicles of the same car class on mpg, msrp, drivetrain, engine, transmission, and safety. 


\section{References}

https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf

https://dplyr.tidyverse.org/

https://tidyr.tidyverse.org/reference/pivot_longer.html

https://ggplot2.tidyverse.org/reference/ggsave.html

http://www.cookbook-r.com/Graphs/Axes_(ggplot2)/

https://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2

https://ggplot2.tidyverse.org/reference/geom_boxplot.html#aesthetics

https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

http://www.statsoft.com/Textbook/Power-Analysis

https://www.statisticssolutions.com/statistical-power-analysis/

https://onezero.blog/combining-multiple-ggplot2-plots-for-scientific-publications/

https://rcompanion.org/handbook/F_12.html


\end{document}
